import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'First Post',
  description: 'Generated by create next app',
}

export default function PostIndex() {
  return (
    <>
      <Head>
        <title>First Post</title>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1>First Post</h1>
        <h2>
          <Link href="/">Back to home</Link>
        </h2>
        <Image
          src="/images/profile.jpg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />
      </main>
    </>
  )
}
